site_name: Terminal Start Guide
nav:
  - Home: "index.md"
  - Set up: "setup.md"
  - Navigation: "navi.md"
  - Creation: "creation1.md"
  - Deletion: "deletion.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossaryterm.md"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
    - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: 2024 Saeyoung and Inez @ Comm 2216
