site_name: Terminal Start Guide
nav:
  - Home: "index.md"
  - Set up: "setup.md"
  - Creation: "creation1.md"
  - Navigation: "navigation1.md"
  - Deletion: "deletion.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossaryterm.md"
  # - Glossary: "glossary1.md"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

copyright: 2024 Saeyoung and Inez @ Comm 2216
